#! /bin/sh

setxkbmap -variant dvorak,

/usr/bin/setxkbmap -option 'caps:ctrl_modifier'
/usr/bin/xcape -e 'Caps_Lock=Escape'

./polybarstart &
pgrep -x sxhkd > /dev/null || sxhkd &

$TERMINAL=~/.local/bin/alacritty
export PATH=$PATH:~/.local/bin
export PATH=$PATH:/usr/local/go/bin

xrandr --output HDMI-2 --primary --mode 1920x1200 --rotate normal --output eDP-1 --mode 1366x768 --rotate normal --left-of HDMI-2

bspc monitor HDMI-2 -d I II III IV V VI VII VIII IX X
bspc monitor eDP-1 -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap           1

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focused_border_color \#32a852 

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Emacs monitor=HDMI-2 state=tiled follow=on
#bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

emacs &
